service:
  host: 0.0.0.0
  port: 8000

kafka:
  bootstrap_servers:
    - localhost:39092
    - localhost:39093
    - localhost:39094

  group_id: document-reader-worker
  topics:
    document_uploaded: document.uploaded
    document_processed: document.processed
    notes_generated: notes.generated

storage:
  base_dir: /data/documents  # بنخزن محلي (وممكن تعتبره simulation لـ S3)
