# version: "3.9"
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.4.0
#     container_name: zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#     ports:
#       - "2181:2181"

#   kafka:
#     image: confluentinc/cp-kafka:7.4.0
#     container_name: kafka
#     depends_on:
#       - zookeeper
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#   kafdrop:
#     image: obsidiandynamics/kafdrop
#     container_name: kafdrop
#     depends_on:
#       - kafka
#     ports:
#       - "19000:9000"
#     environment:
#       KAFKA_BROKERCONNECT: "kafka:29092"
# ----------------------------------------------------------------------------

# version: '3.9'

# services:
#   zookeeper-1:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-1
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32181:2181"
#     networks: [knet]

#   zookeeper-2:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-2
#     environment:
#       ZOOKEEPER_SERVER_ID: 2
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32182:2181"
#     networks: [knet]

#   zookeeper-3:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-3
#     environment:
#       ZOOKEEPER_SERVER_ID: 3
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32183:2181"
#     networks: [knet]

#   kafka-1:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-1
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:39092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafka-2:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-2
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39093:9092"
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://localhost:39093
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafka-3:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-3
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39094:9092"
#     environment:
#       KAFKA_BROKER_ID: 3
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092,EXTERNAL://localhost:39094
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafdrop:
#     image: obsidiandynamics/kafdrop
#     container_name: kafdrop
#     depends_on: [kafka-1, kafka-2, kafka-3]
#     ports:
#       - "39000:9000"
#     environment:
#       KAFKA_BROKERCONNECT: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
#     networks: [knet]

# networks:
#   knet:
#     name: knet












# version: '3.9'

# services:
#   zookeeper-1:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-1
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32181:2181"
#     networks: [knet]

#   zookeeper-2:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-2
#     environment:
#       ZOOKEEPER_SERVER_ID: 2
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32182:2181"
#     networks: [knet]

#   zookeeper-3:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-3
#     environment:
#       ZOOKEEPER_SERVER_ID: 3
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32183:2181"
#     networks: [knet]

#   kafka-1:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-1
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://kafka-1:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafka-2:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-2
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39093:9092"
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://kafka-2:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafka-3:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-3
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39094:9092"
#     environment:
#       KAFKA_BROKER_ID: 3
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092,EXTERNAL://kafka-3:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafdrop:
#     image: obsidiandynamics/kafdrop
#     container_name: kafdrop
#     depends_on: [kafka-1, kafka-2, kafka-3]
#     ports:
#       - "39000:9000"
#     environment:
#       KAFKA_BROKERCONNECT: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
#     networks: [knet]

# networks:
#   knet:
#     name: knet










# version: '3.9'

# services:
#   zookeeper-1:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-1
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32181:2181"
#     networks: [knet]

#   zookeeper-2:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-2
#     environment:
#       ZOOKEEPER_SERVER_ID: 2
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32182:2181"
#     networks: [knet]

#   zookeeper-3:
#     image: confluentinc/cp-zookeeper:7.6.0
#     container_name: zookeeper-3
#     environment:
#       ZOOKEEPER_SERVER_ID: 3
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
#       ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
#     ports:
#       - "32183:2181"
#     networks: [knet]

#   kafka-1:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-1
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://kafka-1:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafka-2:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-2
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39093:9092"
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://kafka-2:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafka-3:
#     image: confluentinc/cp-kafka:7.6.0
#     container_name: kafka-3
#     depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
#     ports:
#       - "39094:9092"
#     environment:
#       KAFKA_BROKER_ID: 3
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092,EXTERNAL://kafka-3:9092
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_MIN_INSYNC_REPLICAS: 2
#     networks: [knet]

#   kafdrop:
#     image: obsidiandynamics/kafdrop
#     container_name: kafdrop
#     depends_on: [kafka-1, kafka-2, kafka-3]
#     ports:
#       - "39000:9000"
#     environment:
#       KAFKA_BROKERCONNECT: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
#     networks: [knet]

# networks:
#   knet:
#     name: knet










version: '3.9'

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    ports:
      - "32181:2181"
    networks: [knet]

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    ports:
      - "32182:2181"
    networks: [knet]

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    ports:
      - "32183:2181"
    networks: [knet]

  kafka-1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-1
    depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
    ports:
      - "39092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:39092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks: [knet]

  kafka-2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-2
    depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
    ports:
      - "39093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://localhost:39093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks: [knet]

  kafka-3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-3
    depends_on: [zookeeper-1, zookeeper-2, zookeeper-3]
    ports:
      - "39094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092,EXTERNAL://localhost:39094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
    networks: [knet]

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on: [kafka-1, kafka-2, kafka-3]
    ports:
      - "39000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
    networks: [knet]

networks:
  knet:
    name: knet
